//! peat-flutter native FFI cdylib.
//!
//! This crate exists only to produce a `staticlib`/`cdylib` (`libpeat_ffi`)
//! from the PUBLISHED `peat-ffi` crate, so the Flutter plugin builds against
//! released crates instead of a `peat` repo checkout. It re-exports peat-ffi's
//! UniFFI scaffolding so the FFI symbols (`uniffi_ffibuffer_*`, checksums,
//! contract version) are exported from the final library and match the
//! hand-maintained Dart bindings in `lib/src/generated/peat_ffi.dart`.
//! There is no API here — everything lives in `peat-ffi`.
// The reexport macro is generated by peat-ffi's `setup_scaffolding!()` and
// exported at its crate root, so it's invoked via the dependency path (not
// `uniffi::`). It forces this cdylib to re-export peat-ffi's FFI scaffolding.
peat_ffi::uniffi_reexport_scaffolding!();
