//! peat-flutter native FFI cdylib.
//!
//! This crate exists only to produce a `staticlib`/`cdylib` (`libpeat_ffi`)
//! from the PUBLISHED `peat-ffi` crate, so the Flutter plugin builds against
//! released crates instead of a `peat` repo checkout. It re-exports peat-ffi's
//! standard UniFFI scaffolding and owns the Dart-specific FFIBuffer adapter, so
//! the final artifact exports the symbols expected by the hand-maintained Dart
//! bindings in `lib/src/generated/peat_ffi.dart`.
//!
//! Protocol behavior remains in the upstream crate. This wrapper only selects
//! features and marshals the Dart calling convention.

pub mod dart_ffi;

// The reexport macro is generated by peat-ffi's `setup_scaffolding!()` and
// exported at its crate root, so it's invoked via the dependency path (not
// `uniffi::`). It forces this cdylib to re-export peat-ffi's FFI scaffolding.
peat_ffi_upstream::uniffi_reexport_scaffolding!();
